/*  glob.h – POSIX-compatible glob for MinGW-64 generated by Grok.
 *  Public domain / MIT – use freely.
 */
#ifndef GLOB_H
#define GLOB_H

#include <stddef.h>     //  for size_t

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    size_t   gl_pathc;   /* Count of paths matched */
    char   **gl_pathv;   /* List of matched paths */
    size_t   gl_offs;    /* Slots to reserve at beginning of gl_pathv */
    /* private fields – do not touch */
    void    *gl_private;
} glob_t;

/* Error return values */
#define GLOB_NOSPACE    1   /* malloc/realloc failed */
#define GLOB_ABORTED    2   /* read error */
#define GLOB_NOMATCH    3   /* no matches */
#define GLOB_ABEND      4   /* unexpected error */

/* Flags */
#define GLOB_ERR        (1 << 0)   /* Return on read errors */
#define GLOB_MARK       (1 << 1)   /* Append '/' to directories */
#define GLOB_NOSORT     (1 << 2)   /* Don't sort results */
#define GLOB_NOCHECK    (1 << 3)   /* Return pattern if no match */
#define GLOB_NOESCAPE   (1 << 4)   /* Disable backslash escaping */
//  NOT supported!
//  #define GLOB_TILDE      (1 << 5)   /* Expand ~ */
//  #define GLOB_BRACE      (1 << 6)   /* Enable {a,b} */
//  #define GLOB_ONLYDIR    (1 << 7)   /* match only directories */
//  #define GLOB_PERIOD     (1 << 8)   /* allow leading '.' */
//  #define GLOB_BRACE      (1 << 9)   /* enable {a,b} expansion */
//  #define GLOB_MAGCHAR    (1 << 10)  /* set if pattern contains magic chars */
//  #define GLOB_ALTDIRFUNC (1 << 11)  /* use alternate directory functions */
//  #define GLOB_NOMAGIC    (1 << 12)  /* treat *?[] as literals if no magic */

//  GNU extensions (optional)
//  #define GLOB_DOOFFS     (1<<12)  /* use gl_offs */
//  #define GLOB_APPEND     (1<<13)  /* append to previous glob_t */

int  glob(const char *pattern ,int flags ,int (*errfunc)(const char *, int) ,glob_t *pglob);
void globfree(glob_t *pglob);

#ifdef __cplusplus
}
#endif

#endif /* GLOB_H */
